jenkins:
  systemMessage: "Shared Jenkins - DevOps Monitoring Project"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  numExecutors: 0 


  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins-node-agent:latest"
              privileged: true
              user: "root"
              mounts:
                - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
              network: "ci-cd_jenkins-network"
            remoteFs: "/home/jenkins/agent"
            mode: EXCLUSIVE
            connector:
              jnlp:
                user: "root"
                jenkinsUrl: "http://jenkins-master:8080"
            instanceCapStr: "10"
            removeVolumes: true
            pullStrategy: PULL_NEVER
            pullTimeout: 300

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              id: github-token
              secret: "${GITHUB_TOKEN}"
              scope: GLOBAL
          - string:
              id: kubeconfig-credential-id
              secret: "${KUBECONFIG_CONTENT}"
              scope: GLOBAL
              description: "Kubernetes config for cluster access"
          - usernamePassword:
              id: dockerhub-credentials
              username: "${DOCKERHUB_USERNAME}"
              password: "${DOCKERHUB_PASSWORD}"
              scope: GLOBAL
              description: "Docker Hub credentials"

jobs:
  - file: /var/jenkins_home/jobs.groovy
